[tool.ruff]
select = ["E", "F", "I", "UP"]
target-version = "py311"
line-length = 120

[tool.black]
target-version =  ["py311"]
line-length = 120

[tool.pytest.ini_options]
addopts = "-ra --cov=src"
testpaths = [
    "src/tests/"
]
pythonpath = ['.']
filterwarnings = [
    "ignore:Glyph:UserWarning"
]

[tool.coverage.report]
show_missing = true
fail_under = 100
